import Link from "next/link";
import { ArrowUpRight, BookOpen, FileText, Folder, Search } from "lucide-react";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { getCurrentUser, hasPermission } from "@/lib/auth/guards";
import { getCurrentWorkspace } from "@/lib/workspaces/current";
import { getDocumentExcerpt } from "@/lib/docs/constants";
import { getDocumentLibrary } from "@/lib/docs/queries";
import { CreateDocumentFolderForm, CreateDocumentForm, DocumentFavoriteForm } from "@/components/docs/forms";
import { TrackedLink } from "@/components/hub/tracked-link";

type SearchParams = Promise<{ folderId?: string; search?: string; page?: string }>;

export default async function DocsLibraryPage({ searchParams }: { searchParams: SearchParams }) {
  const user = await getCurrentUser();
  if (!user) return null;
  const workspace = await getCurrentWorkspace(user.id);
  if (!workspace) return null;
  const params = await searchParams;
  const folderId = params.folderId && /^[0-9a-f-]{36}$/i.test(params.folderId) ? params.folderId : null;
  const search = (params.search ?? "").trim().slice(0, 80);
  const page = Math.max(1, Number.parseInt(params.page ?? "1", 10) || 1);
  const [library, canWrite] = await Promise.all([
    getDocumentLibrary({ userId: user.id, workspaceId: workspace.id, folderId, search, page }),
    hasPermission(workspace.id, "docs.write"),
  ]);
  const totalPages = Math.max(1, Math.ceil(library.totalDocuments / 20));
  const query = new URLSearchParams();
  if (folderId) query.set("folderId", folderId);
  if (search) query.set("search", search);
  const queryString = query.toString();
  const pageTitle = library.breadcrumbs.at(-1)?.name ?? "All documents";

  return <div className="space-y-8"><section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Workspace / Documents</p><h1 className="mt-2 font-display text-4xl font-semibold tracking-tight text-ink">A clear place to think.</h1><p className="mt-3 max-w-2xl text-base leading-7 text-[#667878]">Write in Markdown, keep drafts safe, and share only the pages your {workspace.name} workspace needs.</p></div><div className="flex flex-wrap gap-2"><Link href="/hub"><Button variant="secondary">Back to Hub</Button></Link>{canWrite && <Link href={`/docs/new${folderId ? `?folderId=${folderId}` : ""}`}><Button>New document</Button></Link>}</div></section>
    <section className="grid gap-4 md:grid-cols-3"><Card><CardContent><div className="mb-5 grid h-10 w-10 place-items-center rounded-xl bg-mint text-moss"><BookOpen size={18} /></div><p className="text-sm text-[#667878]">Documents here</p><p className="mt-1 text-3xl font-semibold text-ink">{library.totalDocuments}</p><p className="mt-2 text-xs text-[#8a9992]">Searchable, paginated workspace content.</p></CardContent></Card><Card><CardContent><div className="mb-5 grid h-10 w-10 place-items-center rounded-xl bg-sand text-moss"><FileText size={18} /></div><p className="text-sm text-[#667878]">Recent documents</p><p className="mt-1 text-3xl font-semibold text-ink">{library.recentDocuments.length}</p><p className="mt-2 text-xs text-[#8a9992]">Tracked from your Hub activity.</p></CardContent></Card><Card><CardContent><div className="mb-5 grid h-10 w-10 place-items-center rounded-xl bg-sand text-moss"><Folder size={18} /></div><p className="text-sm text-[#667878]">Folders</p><p className="mt-1 text-3xl font-semibold text-ink">{library.folders.length}</p><p className="mt-2 text-xs text-[#8a9992]">Nested navigation keeps long-lived knowledge calm.</p></CardContent></Card></section>
    {canWrite && <Card><CardHeader><h2 className="font-display text-2xl font-semibold text-ink">Start something useful</h2><p className="mt-1 text-sm text-[#667878]">Create a Markdown document or organize this folder.</p></CardHeader><CardContent className="grid gap-3 lg:grid-cols-2"><CreateDocumentForm workspaceId={workspace.id} folderId={folderId} /><CreateDocumentFolderForm workspaceId={workspace.id} parentId={folderId} /></CardContent></Card>}
    <Card><CardHeader><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex flex-wrap items-center gap-2 text-sm text-[#667878]">{library.breadcrumbs.map((crumb, index) => <span key={crumb.id ?? "root"} className="flex items-center gap-2">{index > 0 && <span className="text-[#b0bbb4]">/</span>}{crumb.id ? <Link href={`/docs?folderId=${crumb.id}${search ? `&search=${encodeURIComponent(search)}` : ""}`} className="hover:text-moss">{crumb.name}</Link> : <Link href={search ? `/docs?search=${encodeURIComponent(search)}` : "/docs"} className="hover:text-moss">{crumb.name}</Link>}</span>)}</div><h2 className="mt-3 font-display text-2xl font-semibold text-ink">{pageTitle}</h2></div><form method="get" className="flex gap-2"><input type="hidden" name="folderId" value={folderId ?? ""} /><Input name="search" defaultValue={search} placeholder="Search titles" aria-label="Search document titles" /><Button type="submit" variant="secondary" aria-label="Search"><Search size={16} /></Button></form></div></CardHeader><CardContent className="space-y-6">{library.recentDocuments.length > 0 && !search && !folderId && <div className="rounded-2xl border border-[var(--line)] bg-sand/30 p-4"><p className="eyebrow">Your trail</p><h3 className="mt-1 font-display text-xl font-semibold text-ink">Recent documents</h3><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{library.recentDocuments.map((document) => <TrackedLink key={document.id} href={`/docs/${document.id}`} workspaceId={workspace.id} entityId={document.id} entityType="document" icon="▤" className="focus-ring flex min-w-0 items-center gap-3 rounded-xl bg-white p-3"><FileText size={15} className="shrink-0 text-moss" /><span className="truncate text-sm font-semibold text-ink">{document.title}</span></TrackedLink>)}</div></div>}
      {canWrite && <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{library.folders.map((folder) => <Link key={folder.id} href={`/docs?folderId=${folder.id}`} className="focus-ring"><Card className="border-[var(--line)] bg-sand/30 transition hover:bg-mint"><CardContent className="flex items-center gap-3 p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white text-moss"><Folder size={18} /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-ink">{folder.name}</span><span className="block text-xs text-[#8a9992]">Document folder</span></span><ArrowUpRight size={15} className="text-[#9aa8a2]" /></CardContent></Card></Link>)}</div>}
      {library.documents.length === 0 && library.folders.length === 0 && <div className="rounded-2xl bg-sand/60 p-8 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-mint text-moss"><BookOpen size={20} /></div><h3 className="mt-4 font-display text-2xl font-semibold text-ink">Nothing written here yet</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#667878]">Start with a short note, a meeting record, or a reusable team guide.</p></div>}
      <div className="divide-y divide-[var(--line)]">{library.documents.map((document) => <div key={document.id} className="flex flex-col gap-3 py-4 first:pt-0 sm:flex-row sm:items-start"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-mint text-moss"><FileText size={18} /></div><div className="min-w-0 flex-1"><TrackedLink href={`/docs/${document.id}`} workspaceId={workspace.id} entityId={document.id} entityType="document" icon="▤" className="focus-ring block truncate text-lg font-semibold text-ink hover:text-moss">{document.title}</TrackedLink><p className="mt-1 line-clamp-2 text-sm leading-6 text-[#667878]">{getDocumentExcerpt(document.content_md) || "Empty draft"}</p><div className="mt-2 flex flex-wrap items-center gap-2"><Badge className={document.status === "published" ? "bg-mint text-moss" : "bg-sand text-[#667878]"}>{document.status}</Badge><Badge className="bg-sand text-[#667878]">{document.visibility}</Badge>{(library.tagNamesByDocument[document.id] ?? []).filter(Boolean).map((tag) => <span key={tag} className="text-xs text-[#8a9992]">#{tag}</span>)}</div></div><div className="flex items-center gap-2"><DocumentFavoriteForm workspaceId={workspace.id} documentId={document.id} favorite={library.favoriteIds.includes(document.id)} /><Link href={`/docs/${document.id}/edit`} className="focus-ring rounded-xl border border-[var(--line)] bg-white px-3 py-2 text-xs font-semibold text-moss">Edit</Link></div></div>)}</div>{totalPages > 1 && <div className="flex items-center justify-between border-t border-[var(--line)] pt-4 text-sm"><span className="text-[#667878]">Page {page} of {totalPages}</span><div className="flex gap-2">{page > 1 && <Link href={`/docs?${withPage(queryString, page - 1)}`} className="rounded-xl border border-[var(--line)] bg-white px-3 py-2 text-xs font-semibold text-moss">Previous</Link>}{page < totalPages && <Link href={`/docs?${withPage(queryString, page + 1)}`} className="rounded-xl border border-[var(--line)] bg-white px-3 py-2 text-xs font-semibold text-moss">Next</Link>}</div></div>}</CardContent></Card>
  </div>;
}

function withPage(queryString: string, page: number) { const params = new URLSearchParams(queryString); params.set("page", String(page)); return params.toString(); }
