"use client";

import { useState } from "react";
import { LayoutGrid, Pin } from "lucide-react";
import { ELYQORA_MODULES, getModuleHref } from "@/lib/modules/registry";
import { togglePinnedModuleAction } from "@/lib/actions/hub";
import { Button } from "@/components/ui/button";

export function ModuleLauncher({ workspaceId, pinnedSlugs = [] }: { workspaceId: string; pinnedSlugs?: string[] }) {
  const [open, setOpen] = useState(false);
  const [pinned, setPinned] = useState(() => new Set(pinnedSlugs));
  return <><Button id="module-launcher" type="button" variant="secondary" className="min-h-10 gap-2 px-3 text-xs" onClick={() => setOpen(true)}><LayoutGrid size={15} />Modules</Button>{open && <div className="fixed inset-0 z-50 grid place-items-start bg-ink/30 p-4 pt-[12vh] backdrop-blur-sm" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><div role="dialog" aria-modal="true" aria-label="Module launcher" className="w-full max-w-2xl rounded-2xl border border-[var(--line)] bg-white p-5 shadow-soft"><div className="mb-5 flex items-start justify-between"><div><p className="eyebrow">Elyqora registry</p><h2 className="mt-2 font-display text-3xl font-semibold text-ink">Open a module</h2></div><button type="button" onClick={() => setOpen(false)} className="focus-ring rounded-xl px-3 py-2 text-sm text-[#667878]">Close</button></div><div className="grid max-h-[60vh] gap-3 overflow-y-auto sm:grid-cols-2">{ELYQORA_MODULES.map((module) => { const isPinned = pinned.has(module.slug); return <div key={module.slug} className={`rounded-2xl border p-4 ${module.enabled ? "border-[var(--line)] bg-white" : "border-dashed border-[var(--line)] bg-sand/50 opacity-60"}`}><div className="flex items-start justify-between gap-3"><a href={module.enabled ? getModuleHref(module) : undefined} onClick={() => { if (module.enabled) setOpen(false); }} className={module.enabled ? "focus-ring flex min-w-0 items-center gap-3" : "flex min-w-0 items-center gap-3"}><span className="grid h-9 w-9 place-items-center rounded-xl bg-mint text-moss">{module.icon}</span><span className="min-w-0"><span className="block truncate text-sm font-semibold text-ink">{module.name}</span><span className="block truncate text-xs text-[#7a8982]">{module.enabled ? module.description : "Planned module"}</span></span></a>{module.enabled && <button type="button" aria-label={`${isPinned ? "Unpin" : "Pin"} ${module.name}`} onClick={() => { const next = !isPinned; setPinned((current) => { const copy = new Set(current); if (next) { copy.add(module.slug); } else { copy.delete(module.slug); } return copy; }); void togglePinnedModuleAction({ workspaceId, moduleSlug: module.slug, pinned: next }); }} className={`focus-ring rounded-lg p-1.5 ${isPinned ? "text-moss" : "text-[#9aa8a2]"}`}><Pin size={15} fill={isPinned ? "currentColor" : "none"} /></button>}</div></div>; })}</div></div></div>}</>;
}
